devel:19/pg_repack: fix dangling Patch0 reference
The makefile-pgxs patch was renamed to the version-less
pg_repack-makefile-pgxs.patch during the devel tier reorganization,
but the spec still referenced the staging-style per-major name
pg_repack-pg%{pgmajorversion}-makefile-pgxs.patch, breaking %prep on
all RPM targets:

  error: File .../SOURCES/pg_repack-pg19-makefile-pgxs.patch: No such
  file or directory

Point Patch0 at the actual file. The patch content still applies to
upstream master (all four hunks, fuzz 1). Debian builds were
unaffected as they do not use this patch.

Signed-off-by: Ricardo Dias <ricardo.dias@percona.com>